# Generated by Django 5.2.3 on 2025-07-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('white', 'Белый'), ('black', 'Чёрный'), ('green', 'Зелёный'), ('red', 'Красный'), ('blue', 'Синий'), ('yellow', 'Жёлтый'), ('beige', 'Бежевый'), ('gray', 'Серый'), ('brown', 'Коричневый'), ('pink', 'Розовый')], max_length=50),
        ),
    ]
