# Generated by Django 4.2.23 on 2025-07-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auth_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код авторизации'),
        ),
    ]
